    name: Deploy MultiContainer Docker
    on:
      push:
        branches:
          - master
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t seatoiler/react-test -f ./client/Dockerfile.dev ./client
          - run: docker run -e CI=true seatoiler/react-test npm test
     
          - run: docker build -t seatoiler/multi-client ./client
          - run: docker build -t seatoiler/multi-nginx ./nginx
          - run: docker build -t seatoiler/multi-server ./server
          - run: docker build -t seatoiler/multi-worker ./worker
     
          - run: docker push seatoiler/multi-client
          - run: docker push seatoiler/multi-nginx
          - run: docker push seatoiler/multi-server
          - run: docker push seatoiler/multi-worker
     
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'
     
          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: multi-docker
              environment_name: Multi-docker-env
              existing_bucket_name: elasticbeanstalk-eu-north-1-905418172981
              region: eu-north-1
              version_label: ${{ github.sha }}
              deployment_package: deploy.zip